# Generated by Django 3.0.6 on 2020-10-31 03:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerdo',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, verbose_name='nombre_cerdo')),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=10, verbose_name='genero')),
                ('peso', models.PositiveSmallIntegerField()),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('edad_ideal', models.PositiveIntegerField()),
                ('peso_ideal', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engorde',
            fields=[
                ('cerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cerdos.Cerdo')),
                ('apto', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nacido',
            fields=[
                ('cerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cerdos.Cerdo')),
                ('apto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reproductor',
            fields=[
                ('cerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cerdos.Cerdo')),
                ('nro_muestras', models.IntegerField()),
                ('nro_hijos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reproductora',
            fields=[
                ('cerdo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cerdos.Cerdo')),
                ('nro_inseminaciones', models.PositiveIntegerField()),
                ('nro_partos', models.PositiveIntegerField()),
                ('fecha_gestacion', models.DateField(default=18)),
                ('embarazo', models.BooleanField(default=False)),
                ('riesgo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cerdoRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(choices=[('Reproductora', 'Reproductora'), ('Reproductor', 'Reproductor'), ('Engorde', 'Engorde'), ('Nacido', 'Nacido')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Cerdo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cerdo',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Raza'),
        ),
    ]
