# Generated by Django 3.1.1 on 2020-09-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerdos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproductora',
            name='fecha_gestacion',
            field=models.DateField(default=17),
        ),
    ]
