# Generated by Django 3.1.6 on 2021-02-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerdos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproductora',
            name='fecha_gestacion',
            field=models.DateField(default=10),
        ),
    ]
