# Generated by Django 3.0.6 on 2020-10-31 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('dni', models.IntegerField()),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
