# Generated by Django 3.0.6 on 2020-08-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=25)),
                ('dni', models.IntegerField()),
                ('vencimiento_carnet', models.DateField()),
            ],
        ),
    ]
