# Generated by Django 3.0.6 on 2020-08-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=50)),
                ('stock_alimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ficha', models.CharField(max_length=50)),
                ('fecha_expiracion', models.DateField(default=9)),
                ('frecuencia_xdia', models.PositiveSmallIntegerField()),
                ('cantidad_xtoma', models.PositiveSmallIntegerField()),
                ('auto_renovar', models.BooleanField(default=False)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.Alimento')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.Cluster')),
            ],
        ),
    ]
