# Generated by Django 3.0.6 on 2020-10-31 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '__first__'),
        ('cerdos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('nombre', models.CharField(max_length=15)),
                ('capacidad', models.PositiveIntegerField(default=20)),
                ('nro_cerdos', models.PositiveIntegerField(default=0)),
                ('nro_galpon', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('personal', models.ManyToManyField(to='personal.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='CerdoCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Cerdo')),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.Cluster')),
            ],
        ),
    ]
