# Generated by Django 3.0.6 on 2020-08-17 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cerdos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_med', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vitamina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vit', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaVitamina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fichavet', models.CharField(max_length=25)),
                ('dias_tratamiento', models.PositiveSmallIntegerField()),
                ('frecuencia_xdia', models.PositiveSmallIntegerField()),
                ('dosis_xtoma', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Cerdo')),
                ('vitamina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacos.Vitamina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FichaVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fichavet', models.CharField(max_length=25)),
                ('dias_tratamiento', models.PositiveSmallIntegerField()),
                ('frecuencia_xdia', models.PositiveSmallIntegerField()),
                ('dosis_xtoma', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Cerdo')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacos.Vacuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FichaMedicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fichavet', models.CharField(max_length=25)),
                ('dias_tratamiento', models.PositiveSmallIntegerField()),
                ('frecuencia_xdia', models.PositiveSmallIntegerField()),
                ('dosis_xtoma', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('cerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerdos.Cerdo')),
                ('medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacos.Medicina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
